### ISSUE TITLE
default.elf inside libnds folder doesn't seem the compiled version of this project

### ISSUE THREAD

**Issue by Zal0** [devkitPro/default-arm7#1]
- make default-arm7
- replace default.elf inside $(DEVKITPRO)/libnds with the generated elf
- compile $(DEVKITPRO)/examples/nds/audio/maxmod/audio_modes
- the generated .nds crashes

Notice this doesn't happen if you use the default.elf already included with libnds
OS: Windows 10 (not sure if this has something to do)

**Comment by WinterMute** [comment]
Replacing default.elf is unsupported.

**Comment by Zal0** [comment]
ok... then 
**[edit] unsupported hackery removed.**
- the generated .nds crashes

Not sure if using ndstool with a custom arm7 program is unsupported too. Some people might need it

**Comment by WinterMute** [comment]
Storming off IRC in the middle of trying to figure out what you're doing isn't a good way to get support.

Look at /opt/devkitpro/examples/nds/templates/combined
