### ISSUE TITLE
"Soft-reset" functionality resets the DS at boot

### ISSUE THREAD

**Issue by kellda** [devkitPro/default-arm7#2]
The soft reset functionality (introduced in 8cd80c97fa729979db95480b061bcbf380218d9b) seems to reset/shutdown the DS. This happens using the latest version installed with dkp-pacman, on both the desmume-glade simulator and an actual DS-lite.

**Comment by WinterMute** [comment]
That's not soft reset functionality, it's a key combo which exits the app. If you run your code via https://github.com/devkitPro/nds-hb-menu/releases/latest then that will return to the menu otherwise it powers off the DS.

**Comment by kellda** [comment]
Thank you for this explanation. My problem here is that the key combo is detected as soon as the game starts. This happens when using the (desmume-glade)[https://desmume.org/] simulator, where REG_KEYCNT returns 0x93 until the first time a key is pressed. More importantly, this also happens on a DS lite using M3DS Real (which I do not know how to debug).

**Comment by WinterMute** [comment]
M3DS Real kernel is broken, would presume desmume glade is also broken tbh. Suggest using the wood M3 kernel instead
 
[m3dsreal-wood-hbmenu-0.9.0.zip](https://github.com/devkitPro/default-arm7/files/13464683/m3dsreal-wood-hbmenu-0.9.0.zip)
